--------------------------------------------------------
--  Fichier créé - mercredi-janvier-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BLOC
--------------------------------------------------------

  CREATE TABLE "AHMEDBA"."BLOC" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM_BLOC" VARCHAR2(20 BYTE), 
	"EQUIPEMENT" VARCHAR2(20 BYTE), 
	"TYPE_EQUIPEMENT" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"DATE_A" VARCHAR2(20 BYTE), 
	"SITUATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENT
--------------------------------------------------------

  CREATE TABLE "AHMEDBA"."EQUIPEMENT" 
   (	"ID_E" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "AHMEDBA"."LOGIN" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AHMEDBA.BLOC
SET DEFINE OFF;
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('121222','sqszqs','qsdsq','sqdsq','20000000','11/02/2000','En marche');
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('121224','sqszqs','qsdsq','sqdsq','20000000','11/02/2000','En panne');
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('121251','sqszqs','qsdsq','sqdsq','20000000','11/02/2000','En panne');
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('121255','sqszqs','qsdsq','sqdsq','20000000','11/02/2000','En marche');
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('122211','ahmed','dggf','dgffgd','27684240','11/11/2000','En marche');
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('111212','ezez','ezez','ezez','22221111','11/11/1111','En panne');
Insert into AHMEDBA.BLOC (ID,NOM_BLOC,EQUIPEMENT,TYPE_EQUIPEMENT,NUMERO,DATE_A,SITUATION) values ('454545','asssss','sqsq','sqssqsq','10101010','11/11/1111','En panne');
REM INSERTING into AHMEDBA.EQUIPEMENT
SET DEFINE OFF;
Insert into AHMEDBA.EQUIPEMENT (ID_E,NOM,NOMBRE,ADRESSE,PRIX,MARQUE) values ('211221','sfsd','sfsfds','fsdf','1211','gujfj');
REM INSERTING into AHMEDBA.LOGIN
SET DEFINE OFF;
Insert into AHMEDBA.LOGIN (NOM,MOT_DE_PASSE) values ('Ahmedba','27684240');
--------------------------------------------------------
--  DDL for Index BLOC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMEDBA"."BLOC_PK" ON "AHMEDBA"."BLOC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMEDBA"."EQUIPEMENT_PK" ON "AHMEDBA"."EQUIPEMENT" ("ID_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMEDBA"."LOGIN_PK" ON "AHMEDBA"."LOGIN" ("NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BLOC
--------------------------------------------------------

  ALTER TABLE "AHMEDBA"."BLOC" ADD CONSTRAINT "BLOC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMEDBA"."BLOC" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENT
--------------------------------------------------------

  ALTER TABLE "AHMEDBA"."EQUIPEMENT" ADD CONSTRAINT "EQUIPEMENT_PK" PRIMARY KEY ("ID_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMEDBA"."EQUIPEMENT" MODIFY ("ID_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "AHMEDBA"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("NOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMEDBA"."LOGIN" MODIFY ("NOM" NOT NULL ENABLE);
